### ISSUE TITLE
An error occurred during compilation: "incompatible types: void cannot be converted to int"

### ISSUE THREAD

**Issue by SuKent** [djpetti/isl-gazecapture#6]
Hi Daniel~

In the process of compiling the Android app, I have an error, can you please guide, thank you!

====================================
Android Studio: "error: incompatible types: void cannot be converted to int"

**GameMainActivity.java**
    // need return int
    gridPos = drawHandler.draw22ClassifiedResult()

**DrawHandler.java**
    // but this return type is void.
    public void draw22ClassifiedResult()
 
_draw33ClassifiedResult() and draw34ClassifiedResult() also have the same problem._

**Comment by djpetti** [comment]
@moutaigua8183 Do you have any ideas about this?

Incidentally, providing more instructions for the app is on my todo list.

**Comment by moutaigua8183** [comment]
@SuKent    without more log info, I can't tell what is the exact problem.  Did you run the game with the server connected?

**Comment by SuKent** [comment]
@moutaigua8183 Hi~

This problem occurs during Android Studio compilation.
The text below is an error message:
     **"error: incompatible types: void cannot be converted to int"**

I found in the source code:
**line: 735 => android_app/app/src/main/java/com/iai/mdf/Activities/Game/GameMainActivity.java**
_// Need to return int type here._
gridPos = drawHandler.draw22ClassifiedResult(relPos, new int[]{holderWidth, holderHeight}, classifiedCircleHolder); break;

**line: 723 => android_app/app/src/main/java/com/iai/mdf/Handlers/DrawHandler.java**
_// But the definition here is void type._     
public void draw22ClassifiedResult(float[] loc, int[] textureSize, FrameLayout panel){

Do you know what I mean?
Thank you for your help!

**Comment by moutaigua8183** [comment]
@SuKent   That's weired. The one you are using is not updated. Mine already has change "void" to "int" types.   Let me upload a new version to the repo

**Comment by moutaigua8183** [comment]
@SuKent   I just created a pull request.  you should be able to see it "Pull requests" tab.
See if it could solve the problem

**Comment by djpetti** [comment]
The pull request is merged. @SuKent please confirm that the compilation issue is resolved.

**Comment by SuKent** [comment]
This issue has been confirmed to be fixed, thanks to @djpetti  and @moutaigua8183  for quick assistance.
